[vm] add log for txn that is kept but has execution error
starcoinorg/starcoin pull request #1253
Opened 2020-09-09 08:10 UTC by guangyuz

2020-09-09 08:24 UTC, fanngyuan approved these changes

2020-09-10 00:29 UTC, jolestar requested changes

2020-09-10 00:29 UTC, jolestar commented on vm/types/src/token/stc.rs
> +pub static WRONG_TOKEN_CODE_FOR_TEST: Lazy<TokenCode> = Lazy::new(|| {
这个同理。

2020-09-10 00:29 UTC, jolestar commented on vm/transaction-builder/src/lib.rs
> +pub fn build_transfer_txn_with_wrong_token_code(
感觉这个方法不应该是 transaction_builder 的一个方法，这个只在测试场景下用，测试的时候直接调用 build_transfer_txn_by_token_type 传个不存在的 TokenType 就行。

2020-09-11 00:38 UTC, jolestar approved these changes

2020-09-11 00:38 UTC, merged