Feature/miner test2
starcoinorg/starcoin pull request #1330
Opened 2020-09-23 08:33 UTC by ssyuan

add miner service test

2020-09-23 10:07 UTC, fikgol approved these changes

2020-09-24 00:19 UTC, jolestar requested changes

2020-09-24 00:19 UTC, jolestar commented on miner/src/create_block_template/mod.rs
> +                    == (self.chain.current_header().number() + MAX_UNCLE_COUNT_PER_BLOCK as u64)
这里的 + 2 不是 MAX_UNCLE_COUNT_PER_BLOCK 的意思。  @tiangong3624749

2020-09-24 04:44 UTC, jolestar approved these changes

2020-09-25 07:16 UTC, merged