[vm] upgrade to 02_20
starcoinorg/starcoin pull request #2194
Opened 2021-02-23 01:09 UTC by guangyuz

- rng upgrade
- move prover upgrade
- use InternalGasUnit 
- resource-viewer adapt to new constraint system
- adapt to session.finish()

2021-02-23 02:56 UTC, jolestar approved these changes

2021-02-23 02:56 UTC, jolestar commented on vm/vm-runtime/src/starcoin_vm.rs
> +            let ap = ap_cache.get_module_path(ModuleId::new(addr, name));
感觉 ap_cache 对我们来说没什么用，我们的 access path 现在没有包含序列化字段了，可以考虑完了清理掉，现在实际也没有实现。这里可以直接用 ModuleId.into 转换成 AccessPath 。

2021-02-23 03:07 UTC, jolestar requested changes
max_gas_amount 以及 gas_constants.maximum_number_of_gas_units 是 GasUnit，不是 InternalGasUnit，比较的时候就不需要 *  gas_unit_scaling_factor 了吧？

https://github.com/starcoinorg/starcoin/blob/06886c75b37f44d1a8c01416d260c3739d7104f7/vm/vm-runtime/src/starcoin_vm.rs#L162

2021-02-23 14:31 UTC, guangyuz commented
> max_gas_amount 以及 gas_constants.maximum_number_of_gas_units 是 GasUnit，不是 InternalGasUnit，比较的时候就不需要 * gas_unit_scaling_factor 了吧？
> 
> https://github.com/starcoinorg/starcoin/blob/06886c75b37f44d1a8c01416d260c3739d7104f7/vm/vm-runtime/src/starcoin_vm.rs#L162

It's fixed.

2021-02-24 02:43 UTC, jolestar approved these changes

2021-02-24 06:36 UTC, merged