add sync task log
starcoinorg/starcoin pull request #3008
Opened 2021-11-03 11:11 UTC by nkysg

add sync task log

2021-11-03 11:50 UTC, jolestar commented on chain/src/chain.rs
> +                let block_hash = self.get_hash_by_number(block_number)?.ok_or_else(|| {
是不是应该直接在 get_hash_by_number 的实现里报错，这样这里的逻辑就没必要动了，因为 chain 内部是知道当前最高的 block_number 是多少的。
不过查询一个超过当前范围的 block number 返回 None 和报错都是有道理的，要考虑下对外的使用场景。

2021-11-03 11:50 UTC, jolestar approved these changes

2021-11-03 11:57 UTC, jolestar commented
修改了一下 pr 的 title

2021-11-04 11:10 UTC, nkysg commented on chain/src/chain.rs
> +                let block_hash = self.get_hash_by_number(block_number)?.ok_or_else(|| {
OK

2021-11-04 15:02 UTC, jolestar commented on cmd/db-checkkey/src/main.rs
> +fn main() -> anyhow::Result<()> {
感觉作为一个独立的 cmd 划不来，也不会默认打包到 docker 镜像中，到时候用的时候得单独编译再弄到镜像里也比较麻烦。

建议：
1. 要么集成在 starcoin 命令中。
2. 要么合并到 db-exporter 中，db exporter 支持导出整个 table，如果要按条件导出，直接增加过滤条件就行。然后把 db-exporter 包括到 docker 镜像中。

2021-11-04 15:05 UTC, jolestar requested changes

2021-11-04 15:05 UTC, jolestar commented on commons/accumulator/src/lib.rs
> +            return Err(format_err!(
超过 num_leaves 应该是返回 None 吧？不应该报错吧？

2021-11-04 15:05 UTC, jolestar commented on commons/accumulator/src/lib.rs
>          self.tree
这里如果是 None 才应该报错吧。这个方法返回 None 代表 leaf_index > num_leaves, 对应的节点不存在，否则就是数据不一致，应该报错，不应该返回 None。

2021-11-05 00:51 UTC, jolestar commented on commons/accumulator/src/lib.rs
>          self.tree
确认一下有测试用例覆盖了这两个 case

2021-11-07 13:48 UTC, jolestar commented on docker/Dockerfile
> +     $RELEASE_PATH/db_exporter \
感觉是不是应该加个 prefix starcoin，这样比较统一，另外如果安装到 path 中也不会重名。

2021-11-07 13:49 UTC, jolestar approved these changes
pr 的 title 可以根据变更内容再修改一下

2021-11-08 02:24 UTC, nkysg commented on docker/Dockerfile
> +     $RELEASE_PATH/db_exporter \
OK

2021-11-08 03:56 UTC, merged