import barnard block and improve apply block print
starcoinorg/starcoin pull request #3054
Opened 2021-11-25 12:48 UTC by nkysg

2021-11-26 01:07 UTC, jolestar requested changes

2021-11-26 01:07 UTC, jolestar commented on scripts/import_barnard_net_block.sh
> +./starcoin_db_exporter apply-block -i $name -n main -o ~/.starcoin/main/
这个 network 和 path 都不对.建议将两个脚本文件合并成一个,通过参数区分,避免重复,也可以降低这种概率.

2021-11-26 01:41 UTC, nkysg commented on scripts/import_barnard_net_block.sh
> +./starcoin_db_exporter apply-block -i $name -n main -o ~/.starcoin/main/
OK，我修改下

2021-11-26 02:27 UTC, nkysg commented on scripts/import_barnard_net_block.sh
> +  ./starcoin_db_exporter apply-block -i $name -n main -o $to_dir
这里network不对

2021-11-29 01:30 UTC, jolestar approved these changes

2021-11-29 01:31 UTC, merged