add get-block-info cmd
starcoinorg/starcoin pull request #3108
Opened 2021-12-22 10:14 UTC by nkysg

2021-12-22 11:06 UTC, jolestar approved these changes
可以顺便把 ChainInfoView 里的 BlockInfo 也改成 BlockInfoView

2021-12-22 11:58 UTC, nkysg commented
> BlockInfo

OK

2021-12-23 14:38 UTC, jolestar commented
@ssyuan @wubuku BlockInfo 这个接口主要 bridge 那边用了，看看这个变更是否影响

2021-12-23 14:40 UTC, jolestar requested changes
等待确认下兼容性问题

2021-12-24 01:58 UTC, wubuku approved these changes
对跨链项目是有一点影响，需要调整一下代码。不过问题不大，注意到了就行。

2021-12-24 02:29 UTC, jolestar approved these changes

2021-12-24 02:31 UTC, jolestar commented
@wubuku 这个合并后会自动部署到 halley network, barnard 上需要发一个新的小版本更新一下。

2021-12-24 02:31 UTC, merged