enlarge max_open_files
starcoinorg/starcoin pull request #3217
Opened 2022-02-17 06:02 UTC by nkysg

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Other information

2022-02-17 07:34 UTC, jolestar approved these changes

2022-02-17 07:40 UTC, jolestar requested changes

2022-02-17 07:40 UTC, jolestar commented on config/src/storage_config.rs
> +        40960
是不是不应该修改这里，应该在 check_open_fds_limit 里保证系统的 limit 要大于 db 的 max_open_files 至少 2 倍？不然 rocksdb 就能把文件打开数给用完了。

2022-02-17 13:46 UTC, nkysg commented on config/src/storage_config.rs
> +        40960
这里设置的是starcoin这个进程用的文件，感觉40960给rocksdb已经够用了，starcoin进程其他可能也要写文件，按你说的给设置个预留的文件数比较保险

2022-02-18 01:48 UTC, jolestar approved these changes

2022-02-18 01:56 UTC, merged