add mpm deploy subcommand
starcoinorg/starcoin pull request #3495
Opened 2022-06-30 05:59 UTC by 0xpause

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #3462 

## What is the new behavior?

- Add `mpm deploy` subcommand.

## Other information

Draft 版本，目前已经将 `starcoin dev deploy` 命令的功能移植到 `mpm deploy`。 使用命令如下：

```
mpm deploy --rpc ws://127.0.0.1:9871 --local-account-dir ~/.starcoin/main/account_vaults/ --password xxxx /path/to/package
```
考虑到 mpm 不应该过度依赖 starcoin node，因此只支持 rpc 链接； 因为需要签名，所以需要 account 已经 password 来unlock 账号。也许将这些 rpc 参数放到一个配置文件， 将密码参数放到一个 .secret 文件中更方便一点？

是否有其他的需求和建议？ @jolestar @WGB5445

2022-06-30 07:01 UTC, WGB5445 commented
我觉得可以增加一个私钥部署的选项，这样更方便，不需要使用 node 保存一个账户信息

2022-06-30 08:04 UTC, 0xpause commented
> 我觉得可以增加一个私钥部署的选项，这样更方便，不需要使用 node 保存一个账户信息

这样确实要方便一些。我研究一下怎么实现。

2022-06-30 15:15 UTC, jolestar commented
> > 以前设计 account provider 的时候考虑过环境变量私钥的 account provider 选项 #3259
> 
> 那这个有没有实现呢？

issue 应该是 #3215 这个。

当时没实现，主要是觉得环境变量不太安全，也可以通过直接将私钥导入到 account db 来实现，因为 console 场景下，account 的所有命令都是可以用的。但如果到 mpm 的场景，还有通过 ci 来部署合约的场景，感觉这个是需要的。

2022-07-03 02:23 UTC, 0xpause commented
> 我觉得可以增加一个私钥部署的选项，这样更方便，不需要使用 node 保存一个账户信息

Done. 

现在同时支持从 local-account-dir 和 secret-file 部署合约。 secret-file 用于保存私钥。 使用命令分别如下：

```
mpm deploy --rpc ws://127.0.0.1:9871 --local-account-dir ~/.starcoin/main/account_vaults/ --password xxxx /path/to/package
mpm deploy --rpc ws://127.0.0.1:9871 --secret-file ~/.starcoin/main/.secret /path/to/package
```

2022-07-03 03:51 UTC, jolestar requested changes

2022-07-03 03:51 UTC, jolestar commented on vm/move-package-manager/src/deployment.rs
> +        sender: Some(package_address),
这里的 sender 不一定是 package_address， Dao 的两阶段升级模式，sender 可以是任何人，所以这里应该从参数中获取。可以考虑把 `TransactionOptions` 直接嵌入到 `DeploymentCommand` 中去。

2022-07-03 04:08 UTC, 0xpause commented on vm/move-package-manager/src/deployment.rs
> +        sender: Some(package_address),
1. “sender 和 package_address 必须相同“，这是参考的 [starcoin dev deploy 命令](https://github.com/starcoinorg/starcoin/blob/5cf407cc64b5ba47a6866677e57140663c5a7a7e/cmd/starcoin/src/dev/deploy_cmd.rs#L45)。所以 starcoin dev deploy 是存在同样的问题吗？
2. TransactionOptions 的 `--gas-price` 选项 和 mpm [Move](https://github.com/starcoinorg/starcoin/blob/5cf407cc64b5ba47a6866677e57140663c5a7a7e/vm/move-package-manager/src/main.rs#L22) 的 `--package` 的 short option `-p` 冲突了，所以才展开自己重新写。

2022-07-03 05:22 UTC, jolestar commented on vm/move-package-manager/src/deployment.rs
> +        sender: Some(package_address),
> 1. “sender 和 package_address 必须相同“，这是参考的 [starcoin dev deploy 命令](https://github.com/starcoinorg/starcoin/blob/5cf407cc64b5ba47a6866677e57140663c5a7a7e/cmd/starcoin/src/dev/deploy_cmd.rs#L45)。所以 starcoin dev deploy 是存在同样的问题吗？

哦，那就有同样的问题。那也可以记个 PR 单独修改这个问题。

2022-07-03 05:25 UTC, jolestar commented on vm/move-package-manager/src/deployment.rs
> +        sender: Some(package_address),
> 2\. TransactionOptions 的 `--gas-price` 选项 和 mpm [Move](https://github.com/starcoinorg/starcoin/blob/5cf407cc64b5ba47a6866677e57140663c5a7a7e/vm/move-package-manager/src/main.rs#L22) 的 `--package` 的 short option `-p` 冲突了，所以才展开自己重新写。

那感觉可以考虑把 `gas-price` 的 short option 给废弃掉？ 大多数情况下不需要指定 gas-price, 这个 option 现在应该还没有广泛使用。

2022-07-03 06:21 UTC, 0xpause commented on account/provider/src/private_key_provider.rs
> +    ) -> Result<Self> {
那 ENV key 是默认、统一的， 还是可以通过命令行选项指定呢？

2022-07-03 06:47 UTC, jolestar commented on account/provider/src/private_key_provider.rs
> +    ) -> Result<Self> {
> 那 ENV key 是默认、统一的， 还是可以通过命令行选项指定呢？

感觉默认统一就好

2022-07-03 06:49 UTC, 0xpause commented on account/provider/src/private_key_provider.rs
> +    ) -> Result<Self> {
那用 STARCOIN_PRIVATE_KEY 怎么样？

2022-07-03 10:55 UTC, 0xpause commented
新增从环境变量读取 private key，设置好私钥的环境变量 `STARCOIN_PRIVATE_KEY` 后，使用如下命令：
```
mpm deploy --rpc ws://127.0.0.1:9871 --from-env /path/to/package
```

2022-07-03 12:15 UTC, 0xpause commented
`run benchmark` 运行到 `use criterion` 步骤时失败了，从日志上也看不出来是哪里错误了。在 [developer-workflow](https://github.com/starcoinorg/starcoin/blob/master/CONTRIBUTING.md#developer-workflow) 只提到了 `./scripts/check_commit.sh`  检查，然而这似乎并不是全部。有更详细明确的文档描述该如何进行提交前的检查吗？

2022-07-03 14:22 UTC, 0xpause commented
> `run benchmark` 运行到 `use criterion` 步骤时失败了，从日志上也看不出来是哪里错误了。在 [developer-workflow](https://github.com/starcoinorg/starcoin/blob/master/CONTRIBUTING.md#developer-workflow) 只提到了 `./scripts/check_commit.sh` 检查，然而这似乎并不是全部。有更详细明确的文档描述该如何进行提交前的检查吗？

重新 rebase master 后提交，run benchmask 运行成功了。也许是上一次提交时，正好遇到其他 PR 被合并了，从而导致 `run benchmark` 失败？

2022-07-04 02:23 UTC, jolestar commented
> > `run benchmark` 运行到 `use criterion` 步骤时失败了，从日志上也看不出来是哪里错误了。在 [developer-workflow](https://github.com/starcoinorg/starcoin/blob/master/CONTRIBUTING.md#developer-workflow) 只提到了 `./scripts/check_commit.sh` 检查，然而这似乎并不是全部。有更详细明确的文档描述该如何进行提交前的检查吗？
> 
> 重新 rebase master 后提交，run benchmask 运行成功了。也许是上一次提交时，正好遇到其他 PR 被合并了，从而导致 `run benchmark` 失败？

benchmark 不太稳定，所以现在主要关注 build and test 这个 task.

2022-07-04 02:27 UTC, jolestar approved these changes
LGTM

2022-07-04 02:28 UTC, merged

2022-07-04 03:25 UTC, 0xpause commented
啥时候更新相关文档比较合适？merge 了就更新，还是等下一次 release 后再更新？

2022-07-04 06:38 UTC, jolestar commented
> 啥时候更新相关文档比较合适？merge 了就更新，还是等下一次 release 后再更新？

文档可以更新了，不过文档那边 merge 之前等这边 release 一个版本。争取这周 release 一个版本吧。

2022-07-13 09:58 UTC, jolestar commented on vm/move-package-manager/src/deployment.rs
> +        sender: Some(package_address),
https://github.com/starcoinorg/starcoin/issues/3527