optimization for the sync
starcoinorg/starcoin pull request #4046
Opened 2024-04-30 04:13 UTC by jackzhhuang

2, fix test cases

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Other information

2024-04-30 05:34 UTC, sanlee42 requested changes

2024-04-30 05:34 UTC, sanlee42 commented on storage/src/lib.rs
> +        StorageVersion::V5
如果是针对main network,  是则是v3->v4，是不是放v4里升了？

2024-04-30 05:34 UTC, sanlee42 commented on flexidag/src/reachability/inquirer.rs
> +                Err(ReachabilityError::HashesNotOrdered)
这里是怎么出现的呢？如果出现了，也就是说会commit失败对吧？能否构造一个复线这个error的case

2024-04-30 05:42 UTC, jackzhhuang commented on storage/src/lib.rs
> +        StorageVersion::V5
是的

2024-04-30 05:48 UTC, jackzhhuang commented on flexidag/src/reachability/inquirer.rs
> +                Err(ReachabilityError::HashesNotOrdered)
多个线程很短时间内重复commit就会失败报HashesNotOrdered，这里增加一个重入的检查，产生这个失败的错误会大大降低，我连续试了10次，也不会再复现了，所以很难再构造这样的error case。

2024-04-30 06:16 UTC, nkysg commented
前面加上dag相关描述吧

2024-05-02 14:12 UTC, sanlee42 approved these changes

2024-05-06 03:12 UTC, merged